STATUS_SERVICE_UNASSIGNED = 0
STATUS_SERVICE_ASSIGNED = 1
STATUS_SERVICE_COMPLETED = 2
STATUS_SERVICE_CANCEL = 3

STATUS_SERVICES = [
    (STATUS_SERVICE_UNASSIGNED, "Unassigned"),
    (STATUS_SERVICE_ASSIGNED, "Assigned"),
    (STATUS_SERVICE_COMPLETED, "Completed"),
    (STATUS_SERVICE_CANCEL, "Canceled"),
]