# Generated by Django 4.1.7 on 2023-02-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_service_destination_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='distance',
            field=models.IntegerField(),
        ),
    ]
