# Generated by Django 4.1.7 on 2023-02-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_driverlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlocation',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
